# -*- coding: utf-8 -*-
"""BigdataProjectPotato.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMuI0Uli9djBhlL5_WuS-cvfFsMNqU0B
"""

import pandas as pd
import numpy as np
#공공데이터 농축산물원천조사가격정보 읽어오기
df101 = pd.read_csv('/content/원천조사가격정보_202101.csv')
df102 = pd.read_csv('/content/원천조사가격정보_202102.csv')
df103 = pd.read_csv('/content/원천조사가격정보_202103.csv')
df104 = pd.read_csv('/content/원천조사가격정보_202104.csv')
df105 = pd.read_csv('/content/원천조사가격정보_202105.csv')
df106 = pd.read_csv('/content/원천조사가격정보_202106.csv')
df107 = pd.read_csv('/content/원천조사가격정보_202107.csv')
df108 = pd.read_csv('/content/원천조사가격정보_202108.csv')
df109 = pd.read_csv('/content/원천조사가격정보_202109.csv')
df110 = pd.read_csv('/content/원천조사가격정보_202110.csv')
df111 = pd.read_csv('/content/원천조사가격정보_202111.csv')
df112 = pd.read_csv('/content/원천조사가격정보_202112.csv')
df201 = pd.read_csv('/content/원천조사가격정보_202201.csv')
df202 = pd.read_csv('/content/원천조사가격정보_202202.csv')
df203 = pd.read_csv('/content/원천조사가격정보_202203.csv')
df204 = pd.read_csv('/content/원천조사가격정보_202204.csv')
df205 = pd.read_csv('/content/원천조사가격정보_202205.csv')
df206 = pd.read_csv('/content/원천조사가격정보_202206.csv')
df207 = pd.read_csv('/content/원천조사가격정보_202207.csv')
df208 = pd.read_csv('/content/원천조사가격정보_202208.csv')

#감자 목록 찾아오기